language: php


notifications:
  email: true

php:
  - nightly # PHP 7.0
  - 5.6
  - 5.5
  - 5.4

env:
  - WP_PROJECT_TYPE=theme 
  - WP_VERSION=latest WP_MULTISITE=0 
  - WP_TEST_URL=http://localhost:12000 
  - WP_TEST_USER=test 
  - WP_TEST_PASS=test

matrix:
  allow_failures:
    - php: nightly

before_script:
 - bash wp-tests/bin/install-wp-tests.sh test root '' localhost $WP_VERSION

script: phpunit