name: PHP

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql:5.7
        env:
            MYSQL_ALLOW_EMPTY_PASSWORD: yes
            MYSQL_DATABASE: wp_test_db
        ports:
            - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3


    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate
      
    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-node-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install dependencies
      if: steps.composer-cache.outputs.cache-hit != 'true'
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Run test suite
      env:
        DB_PORT: ${{ job.services.mysql.ports[3306] }}
      run: | 
       bash bin/install-wp-tests.sh ${{ job.services.mysql.env.MYSQL_DATABASE }} root "" mysql
       vendor/bin/phpunit
       vendor/bin/phpcs --config-set installed_paths vendor/wp-coding-standards/wpcs,vendor/squizlabs/php_codesniffer,vendor/phpcompatibility/php-compatibility,vendor/phpcompatibility/phpcompatibility-wp,vendor/phpcompatibility/phpcompatibility-paragonie
       vendor/bin/phpcs --standard=WordPress --extensions=php --exclude=vendor .
       
    - name: Deploy
      run: 
       echo "${{secrets.DEPLOY_KEY}}" > deploy_key
       rsync -chav --delete \
          -e 'ssh -i ./deploy_key -o StrictHostKeyChecking=no' \
          --exclude /deploy_key \
          --exclude /.git/ \
          --exclude /.github/ \
          --exclude /vendor/ \
          ./ ${{secrets.USER}}@${{secrets.HOST}}:${{secrets.DIR}}
